name: commerce
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  audioplayers: ^6.0.0
  aws_polly: ^2.1.1
  aws_polly_api: ^2.0.0
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  double_back_to_close_app: ^2.1.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  flutter_translate: ^4.0.4
  flutter_tts: ^3.8.5
  fluttertoast: ^8.2.4
  form_validator: ^2.1.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  iconsax: ^0.0.8
  image: ^3.3.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  loading_overlay: ^0.3.0
  path_provider: ^2.1.2
  pin_code_fields: ^8.0.1
  qr_code_scanner: ^1.0.1
  readmore: ^2.2.0
  rename: ^3.0.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  step_progress_indicator: ^1.0.2
  translator: ^1.0.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/label.txt
    - assets/model.tflite
    - assets/mobilenet_v1_1.0_224.tflite
    - assets/mobilenet_v1_1.0_224.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
    - family: PlusJakartaSansMed
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
    - family: PlusJakartaSansBold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
